Repository NeoRazorX/facturascripts, pull requests merged in 2018-02, with the labels that each got.

#306 Añadir el campo personafisica al modelo empresa: modelo, tabla y xmlv…
  Core/Model/Empresa.php
  Core/Table/empresas.xml
  Core/View/EditPageOption.html.twig
  Core/View/Master/DocumentController.html.twig
  Core/View/MegaSearch.html.twig
  Core/XMLView/EditEmpresa.xml
Labels: pending

#311 <bugfix> Fix issue #310 with create folder
  Core/App/AppInstaller.php
Labels: bug, enhancement, pending

#319 Fix for travis
  Test/bootstrap.php
Labels: enhancement

#320 Fixes visual glitches on some BS components.
  Core/Lib/ExtendedController/WidgetItemAutocomplete.php
  Core/View/Macro/DocumentController.html.twig
  Core/View/Macro/ListFilter.html.twig
  Core/View/Master/ListController.html.twig
  Core/View/MegaSearch.html.twig
Labels: enhancement

#321 Translated using Weblate
  Core/Translation/ca_ES.json
  Core/Translation/en_US.json
  Core/Translation/es_AR.json
  Core/Translation/es_CL.json
  Core/Translation/es_CO.json
  Core/Translation/es_DO.json
  Core/Translation/es_ES.json
  Core/Translation/es_GT.json
  Core/Translation/es_MX.json
  Core/Translation/es_PA.json
  Core/Translation/es_PR.json
  Core/Translation/es_US.json
  Core/Translation/fr_FR.json
Labels: enhancement

#323 Trello task 277: Add country list to Data/Lang/EN.
  Core/Data/Lang/EN/paises.csv
Labels: enhancement

#324 Trello task 278: Add currency list to Data/Lang/EN.
  Core/Data/Lang/EN/divisas.csv
Labels: enhancement

#322 Some improvements to Phpblocks
  Core/App/AppController.php
  Core/App/AppInstaller.php
  Core/App/AppRouter.php
  Core/App/WebRender.php
  Core/Base/Controller.php
  Core/Base/DataBase/DataBaseTools.php
  Core/Base/DivisaTools.php
  Core/Base/PluginManager.php
  Core/Controller/DocumentReports.php
  Core/Controller/EditAsiento.php
  Core/Lib/Accounting/AccountingPlanImport.php
  Core/Lib/DocumentReportsBase/DocumentReportsSource.php
  Core/Lib/ExtendedController/DataViewInterface.php
  Core/Lib/ExtendedController/DocumentController.php
  Core/Lib/ExtendedController/DocumentView.php
  Core/Lib/ExtendedController/GridView.php
  Core/Lib/ExtendedController/PanelController.php
  Core/Lib/RandomDataGenerator/AbstractRandom.php
  Core/Lib/RandomDataGenerator/AbstractRandomAccounting.php
  Core/Lib/RandomDataGenerator/AbstractRandomDocuments.php
  Core/Lib/RandomDataGenerator/AbstractRandomPeople.php
  Core/Lib/RandomDataGenerator/Agentes.php
  Core/Lib/RandomDataGenerator/AlbaranesCliente.php
  Core/Lib/RandomDataGenerator/AlbaranesProveedor.php
  Core/Lib/RandomDataGenerator/Articulos.php
  Core/Lib/RandomDataGenerator/ArticulosProveedor.php
  Core/Lib/RandomDataGenerator/Asientos.php
  Core/Lib/RandomDataGenerator/Clientes.php
  Core/Lib/RandomDataGenerator/Cuentas.php
  Core/Lib/RandomDataGenerator/Fabricantes.php
  Core/Lib/RandomDataGenerator/Familias.php
  Core/Lib/RandomDataGenerator/Grupos.php
  Core/Lib/RandomDataGenerator/PedidosCliente.php
  Core/Lib/RandomDataGenerator/PedidosProveedor.php
  Core/Lib/RandomDataGenerator/PresupuestosCliente.php
  Core/Lib/RandomDataGenerator/Proveedores.php
  Core/Lib/RandomDataGenerator/Subcuentas.php
  Core/Model/Articulo.php
  Core/Model/Asiento.php
  Core/Model/Base/Address.php
  Core/Model/Cuenta.php
  Core/Model/Partida.php
Labels: enhancement
