Repository NeoRazorX/facturascripts, pull requests merged in 2018-04, with the labels that each got.

#359 Trello task 293, modify EditPageOption to go back to real page.
  Core/Controller/EditPageOption.php
  Core/View/EditPageOption.html.twig
  Core/View/Master/ListController.html.twig
  Core/View/Master/PanelController.html.twig
Labels: pending

#365 Trello task 312
  Core/Controller/Randomizer.php
  Core/Lib/RandomDataGenerator/PresupuestosProveedor.php
  Core/Model/PresupuestoProveedor.php
  Core/Translation/en_EN.json
  Core/View/Randomizer.html.twig
  Test/Core/Model/AlbaranClienteTest.php
  Test/Core/Model/AlbaranProveedorTest.php
  Test/Core/Model/RegularizacionStockTest.php
  Test/Core/Model/TransferenciaStockTest.php
Labels: pending

#372 Implement authentication via token for API. Trello Issue 94
  Core/App/AppAPI.php
  Core/Model/ApiKey.php
Labels: enhancement

#399 Added basic and generic test for all models
  Core/Model/Base/ModelClass.php
Labels: pending

#409 Added tab with a list of lines from delivery notes (Trello task 326)
  Core/Controller/ListAlbaranCliente.php
  Core/Translation/en_EN.json
  Core/XMLView/ListLineaAlbaranCliente.xml
Labels: pending

#403 Refactoring the API library
  Core/App/AppAPI.php
  Core/Lib/API/APIModel.php
  Core/Lib/API/Base/APIResourceClass.php
  Core/Lib/API/Calculate.php
Labels: invalid, pending

#400 Added SettingsLog.xml to allow end user to select what messages store in database
  Core/Controller/EditLogMessage.php
  Core/Controller/ListLogMessage.php
  Core/Model/LogMessage.php
  Core/Table/logs.xml
  Core/Translation/en_EN.json
  Core/Translation/es_ES.json
  Core/XMLView/EditLogMessage.xml
  Core/XMLView/ListLogMessage.xml
  Core/XMLView/SettingsLog.xml
Labels: invalid, pending

#397 fs2018: Trello task #321 fixed ledger report when is requested not grouped
  Core/Lib/Accounting/Ledger.php
Labels: invalid
